StomatoloskaOrdinacija/Controllers/NarudzbaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StomatoloskaOrdinacija.DAL;
using StomatoloskaOrdinacija.Domain.DTOs;
using StomatoloskaOrdinacija.Domain.Services;

namespace StomatoloskaOrdinacija.Controllers
{
    public class NarudzbaController : Controller
    {
        private OrdinacijaDb db = new OrdinacijaDb();
        NarudzbeService service = new NarudzbeService();

        // GET: Narudzba
        public ActionResult Popis()
        {
            var res = service.GetPopisNarudzba();
            return View(res);
        }

        // GET: Narudzba/Create
        public ActionResult Izradi()
        {
            var narudzba = service.GetEmptyNarudzba();
            return View(narudzba);
        }

        // POST: Narudzba/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Izradi([Bind(Include = "ID,Datum,Sati,Minute,Opis,PacijentID,ZahvatID,Dolazak")] NarudzbaDTO narudzbaDTO)
        {
            if (ModelState.IsValid)
            {
                service.CreateNewNarudzba(narudzbaDTO);

                return RedirectToAction("Popis");
            }

            service.FillDDLPacijentZahvat(narudzbaDTO);

            return View(narudzbaDTO);
        }

        // GET: Narudzba/Edit/5
        public ActionResult Uredi(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NarudzbaDTO narudzbaDTO = service.GetNarudzbaById(id);
            if (narudzbaDTO == null)
            {
                return HttpNotFound();
            }
            //ViewBag.PacijentID = new SelectList(db.Pacijents, "ID", "Ime", narudzbaDTO.PacijentID);
            //ViewBag.ZahvatID = new SelectList(db.Zahvats, "ID", "Sifra", narudzbaDTO.ZahvatID);
            return View(narudzbaDTO);
        }

        // POST: Narudzba/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Uredi([Bind(Include = "ID,Datum,Sati,Minute,Opis,PacijentID,ZahvatID,Dolazak")] NarudzbaDTO narudzbaDTO)
        {
            if (ModelState.IsValid)
            {
                service.EditNarudzba(narudzbaDTO);

                return RedirectToAction("Popis");
            }
            //ViewBag.PacijentID = new SelectList(db.Pacijents, "ID", "Ime", narudzbaDTO.PacijentID);
            //ViewBag.ZahvatID = new SelectList(db.Zahvats, "ID", "Sifra", narudzbaDTO.ZahvatID);
            return View(narudzbaDTO);
        }

        // GET: Narudzba/Delete/5
        public ActionResult Izbrisi(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            NarudzbaDTO narudzbaDTO = service.GetNarudzbaById(id);

            if (narudzbaDTO == null)
            {
                return HttpNotFound();
            }
            return View(narudzbaDTO);
        }

        // POST: Narudzba/Delete/5
        [HttpPost, ActionName("Izbrisi")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NarudzbaDTO narudzbaDTO = service.GetNarudzbaById(id);

            service.DeleteNarudzba(narudzbaDTO);

            return RedirectToAction("Popis");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

StomatoloskaOrdinacija/Controllers/NaslovnicaController.cs
using StomatoloskaOrdinacija.Domain.DTOs;
using StomatoloskaOrdinacija.Domain.Services;
using StomatoloskaOrdinacija.Domain.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StomatoloskaOrdinacija.Controllers
{
    [Authorize]
    public class NaslovnicaController : Controller
    {
        RadnoVrijemeService radnoVrijemeService = new RadnoVrijemeService();
        NarudzbeService narudzbaService = new NarudzbeService();

        // GET: Naslovnica
        public ActionResult Kalendar()
        {
            NarudzbaRadnoVrijemeVM viewModel = new NarudzbaRadnoVrijemeVM();
            viewModel.NarudzbaDTOList = GetNarudzbaList();
            viewModel.RadnoVrijemeDTO = GetRadnoVrijeme();

            return View(viewModel);
        }

        public List<NarudzbaDTO> GetNarudzbaList()
        {
            List<NarudzbaDTO> narudzbaDTO = narudzbaService.GetPopisNarudzba();

            return narudzbaDTO;
        }

        public RadnoVrijemeDTO GetRadnoVrijeme()
        {
            var id = radnoVrijemeService.GetRadnoVrijemeId();
            RadnoVrijemeDTO radnoVrijemeDTO = radnoVrijemeService.GetRadnoVrijemeById(id);

            return radnoVrijemeDTO;
        }
    }
}

StomatoloskaOrdinacija/Views/Narudzba/Create.cshtml
@model StomatoloskaOrdinacija.Domain.DTOs.NarudzbaDTO

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>NarudzbaDTO</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Datum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Datum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Datum, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-inline">
        @Html.LabelFor(model => model.Sati, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sati, new { htmlAttributes = new { @class = "form-control col-md-2" } })
            @Html.ValidationMessageFor(model => model.Sati, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-inline">
        @Html.LabelFor(model => model.Minute, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Minute, new { htmlAttributes = new { @class = "form-control col-md-2" } })
            @Html.ValidationMessageFor(model => model.Minute, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PacijentID, "PacijentID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.PacijentID, Model.PacijentListDTO, "- Odaberite pacijenta -", new { @class = "btn btn-default" })
            @Html.ValidationMessageFor(model => model.PacijentID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ZahvatID, "ZahvatID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.ZahvatID, Model.ZahvatListDTO, "- Odaberite zahvat -", new { @class = "btn btn-default" })
            @Html.ValidationMessageFor(model => model.ZahvatID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Dolazak, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Dolazak)
                @Html.ValidationMessageFor(model => model.Dolazak, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StomatoloskaOrdinacija/Views/Narudzba/Delete.cshtml
@model StomatoloskaOrdinacija.Domain.DTOs.NarudzbaDTO

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NarudzbaDTO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Vrijeme)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vrijeme)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dolazak)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dolazak)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StomatoloskaOrdinacija/Views/Narudzba/Edit.cshtml
@model StomatoloskaOrdinacija.Domain.DTOs.NarudzbaDTO

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>NarudzbaDTO</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="form-group">
        @Html.LabelFor(model => model.Datum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Datum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Datum, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-inline">
        @Html.LabelFor(model => model.Sati, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sati, new { htmlAttributes = new { @class = "form-control col-md-2" } })
            @Html.ValidationMessageFor(model => model.Sati, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-inline">
        @Html.LabelFor(model => model.Minute, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Minute, new { htmlAttributes = new { @class = "form-control col-md-2" } })
            @Html.ValidationMessageFor(model => model.Minute, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PacijentID, "PacijentID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.PacijentID, Model.PacijentListDTO, "- Odaberite pacijenta -", new { @class = "btn btn-default" })
            @Html.ValidationMessageFor(model => model.PacijentID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ZahvatID, "ZahvatID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.ZahvatID, Model.ZahvatListDTO, "- Odaberite zahvat -", new { @class = "btn btn-default" })
            @Html.ValidationMessageFor(model => model.ZahvatID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Dolazak, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Dolazak)
                @Html.ValidationMessageFor(model => model.Dolazak, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StomatoloskaOrdinacija/Views/Narudzba/Izbrisi.cshtml
@model StomatoloskaOrdinacija.Domain.DTOs.NarudzbaDTO

@{
    ViewBag.Title = "Izbriši narudžbu";
}

<h2>@ViewBag.Title</h2>

<h3>Jeste li sigurni da želite obrisati ovu stavku?</h3>
<div>
    <h4>Narudžba</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Vrijeme)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vrijeme)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dolazak)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dolazak)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Izbriši" class="btn btn-danger" /> |
            @Html.ActionLink("Povratak na popis", "Popis", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

StomatoloskaOrdinacija/Views/Narudzba/Izradi.cshtml
@model StomatoloskaOrdinacija.Domain.DTOs.NarudzbaDTO

@{
    ViewBag.Title = "Nova narudžba";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Datum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Datum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Datum, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-inline">
        @Html.LabelFor(model => model.Sati, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sati, new { htmlAttributes = new { @class = "form-control col-md-2" } })
            @Html.ValidationMessageFor(model => model.Sati, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-inline">
        @Html.LabelFor(model => model.Minute, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Minute, new { htmlAttributes = new { @class = "form-control col-md-2" } })
            @Html.ValidationMessageFor(model => model.Minute, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PacijentID, "Pacijent", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.PacijentID, Model.PacijentListDTO, "- Odaberite pacijenta -", new { @class = "btn btn-default" })
            @Html.ValidationMessageFor(model => model.PacijentID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ZahvatID, "Zahvat", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.ZahvatID, Model.ZahvatListDTO, "- Odaberite zahvat -", new { @class = "btn btn-default" })
            @Html.ValidationMessageFor(model => model.ZahvatID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Izradi" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Povratak na popis", "Popis", null, new { @class = "btn btn-default"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StomatoloskaOrdinacija/Views/Narudzba/Popis.cshtml
@model IEnumerable<StomatoloskaOrdinacija.Domain.DTOs.NarudzbaDTO>

@{
    ViewBag.Title = "Popis narudžbi";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Nova narudžba", "Izradi", null, new { @class = "btn btn-default"})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Vrijeme)
        </th>
        <th>
            @Html.DisplayName("Vrijeme završetka")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Opis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dolazak)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PacijentID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZahvatID)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Vrijeme)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VrijemeZavrsetkaZahvata)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Opis)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dolazak)
        </td>
        <td>
            @Html.DropDownListFor(modelItem => item.PacijentID, item.PacijentListDTO, null, null)
        </td>
        <td>
            @Html.DropDownListFor(modelItem => item.ZahvatID, item.ZahvatListDTO, null, null)
        </td>
        <td>
            @Html.ActionLink("Uredi", "Uredi", new { id = item.ID }, new { @class = "btn btn-default" }) |
            @Html.ActionLink("Izbriši", "Izbrisi", new { id = item.ID }, new { @class = "btn btn-default" })
        </td>
    </tr>
}
</table>
<p>
    @Html.ActionLink("Kalendar", "Kalendar", "Naslovnica", null, new { @class = "btn btn-default" })
</p>

StomatoloskaOrdinacija/Views/Narudzba/Uredi.cshtml
@model StomatoloskaOrdinacija.Domain.DTOs.NarudzbaDTO

@{
    ViewBag.Title = "Uredi narudžbu";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="form-group">
        @Html.LabelFor(model => model.Datum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Datum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Datum, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-inline">
        @Html.LabelFor(model => model.Sati, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sati, new { htmlAttributes = new { @class = "form-control col-md-2" } })
            @Html.ValidationMessageFor(model => model.Sati, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-inline">
        @Html.LabelFor(model => model.Minute, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Minute, new { htmlAttributes = new { @class = "form-control col-md-2" } })
            @Html.ValidationMessageFor(model => model.Minute, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PacijentID, "Pacijent", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.PacijentID, Model.PacijentListDTO, "- Odaberite pacijenta -", new { @class = "btn btn-default" })
            @Html.ValidationMessageFor(model => model.PacijentID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ZahvatID, "Zahvat", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.ZahvatID, Model.ZahvatListDTO, "- Odaberite zahvat -", new { @class = "btn btn-default" })
            @Html.ValidationMessageFor(model => model.ZahvatID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Dolazak, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Dolazak)
                @Html.ValidationMessageFor(model => model.Dolazak, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Spremi" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Povratak na popis", "Popis", null, new { @class = "btn btn-default"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}