StomatoloskaOrdinacija/Controllers/NarudzbaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StomatoloskaOrdinacija.DAL;
using StomatoloskaOrdinacija.Domain.DTOs;
using StomatoloskaOrdinacija.Domain.Services;

namespace StomatoloskaOrdinacija.Controllers
{
    public class NarudzbaController : Controller
    {
        private OrdinacijaDb db = new OrdinacijaDb();
        NarudzbeService service = new NarudzbeService();

        // GET: Narudzba
        public ActionResult Popis()
        {
            var res = service.GetPopisNarudzba();
            return View(res);
        }

        // GET: Narudzba/Create
        public ActionResult Izradi()
        {
            var narudzba = service.GetEmptyNarudzba();
            return View(narudzba);
        }

        // POST: Narudzba/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Izradi([Bind(Include = "ID,Datum,Sati,Minute,Opis,PacijentID,ZahvatID,Dolazak")] NarudzbaDTO narudzbaDTO)
        {
            if (ModelState.IsValid)
            {
                service.CreateNewNarudzba(narudzbaDTO);

                return RedirectToAction("Popis");
            }

            service.FillDDLPacijentZahvat(narudzbaDTO);

            return View(narudzbaDTO);
        }

        // GET: Narudzba/Edit/5
        public ActionResult Uredi(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NarudzbaDTO narudzbaDTO = service.GetNarudzbaById(id);
            if (narudzbaDTO == null)
            {
                return HttpNotFound();
            }
            //ViewBag.PacijentID = new SelectList(db.Pacijents, "ID", "Ime", narudzbaDTO.PacijentID);
            //ViewBag.ZahvatID = new SelectList(db.Zahvats, "ID", "Sifra", narudzbaDTO.ZahvatID);
            return View(narudzbaDTO);
        }

        // POST: Narudzba/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Uredi([Bind(Include = "ID,Datum,Sati,Minute,Opis,PacijentID,ZahvatID,Dolazak")] NarudzbaDTO narudzbaDTO)
        {
            if (ModelState.IsValid)
            {
                service.EditNarudzba(narudzbaDTO);

                return RedirectToAction("Popis");
            }
            //ViewBag.PacijentID = new SelectList(db.Pacijents, "ID", "Ime", narudzbaDTO.PacijentID);
            //ViewBag.ZahvatID = new SelectList(db.Zahvats, "ID", "Sifra", narudzbaDTO.ZahvatID);
            return View(narudzbaDTO);
        }

        // GET: Narudzba/Delete/5
        public ActionResult Izbrisi(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            NarudzbaDTO narudzbaDTO = service.GetNarudzbaById(id);

            if (narudzbaDTO == null)
            {
                return HttpNotFound();
            }
            return View(narudzbaDTO);
        }

        // POST: Narudzba/Delete/5
        [HttpPost, ActionName("Izbrisi")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NarudzbaDTO narudzbaDTO = service.GetNarudzbaById(id);

            service.DeleteNarudzba(narudzbaDTO);

            return RedirectToAction("Popis");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

StomatoloskaOrdinacija/Controllers/NaslovnicaController.cs
using StomatoloskaOrdinacija.Domain.DTOs;
using StomatoloskaOrdinacija.Domain.Services;
using StomatoloskaOrdinacija.Domain.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StomatoloskaOrdinacija.Controllers
{
    [Authorize]
    public class NaslovnicaController : Controller
    {
        RadnoVrijemeService radnoVrijemeService = new RadnoVrijemeService();
        NarudzbeService narudzbaService = new NarudzbeService();

        // GET: Naslovnica
        public ActionResult Kalendar()
        {
            NarudzbaRadnoVrijemeVM viewModel = new NarudzbaRadnoVrijemeVM();
            viewModel.NarudzbaDTOList = GetNarudzbaList();
            viewModel.RadnoVrijemeDTO = GetRadnoVrijeme();

            return View(viewModel);
        }

        public List<NarudzbaDTO> GetNarudzbaList()
        {
            List<NarudzbaDTO> narudzbaDTO = narudzbaService.GetPopisNarudzba();

            return narudzbaDTO;
        }

        public RadnoVrijemeDTO GetRadnoVrijeme()
        {
            var id = radnoVrijemeService.GetRadnoVrijemeId();
            RadnoVrijemeDTO radnoVrijemeDTO = radnoVrijemeService.GetRadnoVrijemeById(id);

            return radnoVrijemeDTO;
        }
    }
}

StomatoloskaOrdinacija/Views/Naslovnica/Kalendar.cshtml
@using StomatoloskaOrdinacija.Domain.ViewModels;
@model NarudzbaRadnoVrijemeVM

@{ List<string> view = new List<string>() { "Day", "WorkWeek" };

    List<object> Narudzba = new List<object>();
    foreach (var item in Model.NarudzbaDTOList)
    {
        Narudzba.Add(item);
    }

    var vrijemeOd = Model.RadnoVrijemeDTO.VrijemeOd;
    var vrijemeDo = Model.RadnoVrijemeDTO.VrijemeDo;
}

@{int counter = 0;
    foreach (var item in Model.NarudzbaDTOList)
    {
        counter++;
        if (item.Dolazak == true)
        {
            <style>
                #Appointment_@counter {
                    background: linear-gradient(to bottom,#95a5a6 0%,#95a5a6 100%) !important;
                }
            </style>
        }
    }
}

<h2>Kalendar narudžbi</h2>
<hr />
@Html.ActionLink("Nova narudžba", "Izradi", "Narudzba", null, new { @class="btn btn-default"})
<br /><br />
@(Html.EJ().Schedule("Schedule1")
                    .Width("100%")
                    .Height("525px")
                    .CurrentDate(DateTime.Now)
                    .TimeZone("UTC +01:00")
                    .StartHour(vrijemeOd)
                    .EndHour(vrijemeDo)
                    .Locale("hr-HR")
                    .Views(view)
                    .ShowQuickWindow(false)
                    .ReadOnly(true)
                    .ShowAppointmentNavigator(true)
                    .ShowAllDayRow(false)
                    .EnableAppointmentResize(false)
                    .AllowDragAndDrop(false)
                    .TimeMode(TimeMode.Hour24)
                    .DateFormat("dd.MM.yyyy")
                    .AppointmentSettings(fields => fields.Datasource(Narudzba)
                        .Id("ID")
                        .Subject("Opis")
                        .StartTime("Vrijeme")
                        .EndTime("VrijemeZavrsetkaZahvata")
                        )
                    .ScheduleClientSideEvents(evt => evt.AppointmentWindowOpen("onAppointmentWindowOpen"))
)
<script>
    function onAppointmentWindowOpen(args) {
        args.cancel = true;
    }
</script>