StomatoloskaOrdinacija/Controllers/CijenaZahvataController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StomatoloskaOrdinacija.DAL;
using StomatoloskaOrdinacija.Domain.DTOs;
using StomatoloskaOrdinacija.Domain.Services;

namespace StomatoloskaOrdinacija.Controllers
{
    public class CijenaZahvataController : Controller
    {
        private OrdinacijaDb db = new OrdinacijaDb();
        CijeneZahvataService service = new CijeneZahvataService();

        // GET: CijenaZahvata
        public ActionResult Popis()
        {
            var res = service.GetPopisCijenaZahvata();
            return View(res);
        }

        // GET: CijenaZahvata/Create
        public ActionResult Izradi()
        {
            return View();
        }

        // POST: CijenaZahvata/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Izradi([Bind(Include = "ID,Cijena")] CijenaZahvataDTO cijenaZahvataDTO)
        {
            if (ModelState.IsValid)
            {
                service.CreateNewCijenaZahvata(cijenaZahvataDTO);

                return RedirectToAction("Popis");
            }

            return View(cijenaZahvataDTO);
        }

        // GET: CijenaZahvata/Edit/5
        public ActionResult Uredi(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CijenaZahvataDTO cijenaZahvataDTO = service.GetCijenaZahvataById(id);
            if (cijenaZahvataDTO == null)
            {
                return HttpNotFound();
            }
            return View(cijenaZahvataDTO);
        }

        // POST: CijenaZahvata/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Uredi([Bind(Include = "ID,Cijena")] CijenaZahvataDTO cijenaZahvataDTO)
        {
            if (ModelState.IsValid)
            {
                service.EditCijenaZahvata(cijenaZahvataDTO);

                return RedirectToAction("Popis");
            }
            return View(cijenaZahvataDTO);
        }

        // GET: CijenaZahvata/Delete/5
        public ActionResult Izbrisi(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CijenaZahvataDTO cijenaZahvataDTO = service.GetCijenaZahvataById(id);
            if (cijenaZahvataDTO == null)
            {
                return HttpNotFound();
            }
            return View(cijenaZahvataDTO);
        }

        // POST: CijenaZahvata/Delete/5
        [HttpPost, ActionName("Izbrisi")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CijenaZahvataDTO cijenaZahvataDTO = service.GetCijenaZahvataById(id);

            service.DeleteCijenaZahvata(cijenaZahvataDTO);

            return RedirectToAction("Popis");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StomatoloskaOrdinacija/Controllers/TrajanjeZahvataController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StomatoloskaOrdinacija.DAL;
using StomatoloskaOrdinacija.Domain.DTOs;
using StomatoloskaOrdinacija.Domain.Services;

namespace StomatoloskaOrdinacija.Controllers
{
    public class TrajanjeZahvataController : Controller
    {
        private OrdinacijaDb db = new OrdinacijaDb();
        TrajanjeZahvataService service = new TrajanjeZahvataService();

        // GET: TrajanjeZahvata
        public ActionResult Popis()
        {
            var res = service.GetPopisTrajanjeZahvata();
            return View(res);
        }

        // GET: TrajanjeZahvata/Create
        public ActionResult Izradi()
        {
            return View();
        }

        // POST: TrajanjeZahvata/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Izradi([Bind(Include = "ID,Trajanje")] TrajanjeZahvataDTO trajanjeZahvataDTO)
        {
            if (ModelState.IsValid)
            {
                service.CreateNewTrajanjeZahvata(trajanjeZahvataDTO);

                return RedirectToAction("Popis");
            }

            return View(trajanjeZahvataDTO);
        }

        // GET: TrajanjeZahvata/Edit/5
        public ActionResult Uredi(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrajanjeZahvataDTO trajanjeZahvataDTO = service.GetTrajanjeZahvataById(id);
            if (trajanjeZahvataDTO == null)
            {
                return HttpNotFound();
            }
            return View(trajanjeZahvataDTO);
        }

        // POST: TrajanjeZahvata/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Uredi([Bind(Include = "ID,Trajanje")] TrajanjeZahvataDTO trajanjeZahvataDTO)
        {
            if (ModelState.IsValid)
            {
                service.EditTrajanjeZahvata(trajanjeZahvataDTO);

                return RedirectToAction("Popis");
            }
            return View(trajanjeZahvataDTO);
        }

        // GET: TrajanjeZahvata/Delete/5
        public ActionResult Izbrisi(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrajanjeZahvataDTO trajanjeZahvataDTO = service.GetTrajanjeZahvataById(id);
            if (trajanjeZahvataDTO == null)
            {
                return HttpNotFound();
            }
            return View(trajanjeZahvataDTO);
        }

        // POST: TrajanjeZahvata/Delete/5
        [HttpPost, ActionName("Izbrisi")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TrajanjeZahvataDTO trajanjeZahvataDTO = service.GetTrajanjeZahvataById(id);

            service.DeleteTrajanjeZahvata(trajanjeZahvataDTO);

            return RedirectToAction("Popis");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StomatoloskaOrdinacija/Controllers/ZahvatiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StomatoloskaOrdinacija.DAL;
using StomatoloskaOrdinacija.Domain.DTOs;
using StomatoloskaOrdinacija.Domain.Services;

namespace StomatoloskaOrdinacija.Controllers
{
    public class ZahvatiController : Controller
    {
        private OrdinacijaDb db = new OrdinacijaDb();
        ZahvatiService service = new ZahvatiService();

        // GET: Zahvati
        public ActionResult Popis()
        {
            var res = service.GetPopisZahvata();
            return View(res);
        }

        // GET: Zahvati/Details/5
        public ActionResult Detalji(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ZahvatDTO zahvatDTO = service.GetZahvatById(id);
            if (zahvatDTO == null)
            {
                return HttpNotFound();
            }
            return View(zahvatDTO);
        }

        // GET: Zahvati/Create
        public ActionResult Izradi()
        {
            var zahvat = service.GetEmptyZahvat();
            return View(zahvat);
        }

        // POST: Zahvati/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Izradi([Bind(Include = "ID,Sifra,Naziv,CijenaID,TrajanjeID,Cijena,Trajanje")] ZahvatDTO zahvatDTO)
        {
            if (ModelState.IsValid)
            {
                service.CreateNewZahvat(zahvatDTO);

                return RedirectToAction("Popis");
            }

            service.FillDDLPacijentTrajanje(zahvatDTO);
            return View(zahvatDTO);
        }

        // GET: Zahvati/Edit/5
        public ActionResult Uredi(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ZahvatDTO zahvatDTO = service.GetZahvatById(id);
            if (zahvatDTO == null)
            {
                return HttpNotFound();
            }
            return View(zahvatDTO);
        }

        // POST: Zahvati/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Uredi([Bind(Include = "ID,Sifra,Naziv,CijenaID,TrajanjeID,Cijena,Trajanje")] ZahvatDTO zahvatDTO)
        {
            if (ModelState.IsValid)
            {
                service.EditZahvat(zahvatDTO);

                return RedirectToAction("Popis");
            }
            return View(zahvatDTO);
        }

        // GET: Zahvati/Delete/5
        public ActionResult Izbrisi(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ZahvatDTO zahvatDTO = service.GetZahvatById(id);
            if (zahvatDTO == null)
            {
                return HttpNotFound();
            }
            return View(zahvatDTO);
        }

        // POST: Zahvati/Delete/5
        [HttpPost, ActionName("Izbrisi")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ZahvatDTO zahvatDTO = service.GetZahvatById(id);

            service.DeleteZahvat(zahvatDTO);

            return RedirectToAction("Popis");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StomatoloskaOrdinacija/Views/Zahvati/Create.cshtml
@model StomatoloskaOrdinacija.Domain.DTOs.ZahvatDTO

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ZahvatDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Sifra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sifra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sifra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cijena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CijenaID, Model.CijenaListDTO, "- Odaberite cijenu -", new { @class = "btn btn-default" }) 
                @Html.ActionLink("Dodaj cijenu zahvata", "Index", "CijenaZahvata", null, new { @class = "btn btn-default" })
                @Html.ValidationMessageFor(model => model.CijenaID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Trajanje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TrajanjeID, Model.TrajanjeListDTO, "- Odaberite trajanje -", new { @class = "btn btn-default" })
                @Html.ActionLink("Dodaj trajanje zahvata", "Index", "TrajanjeZahvata", null, new { @class = "btn btn-default" })
                @Html.ValidationMessageFor(model => model.TrajanjeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StomatoloskaOrdinacija/Views/Zahvati/Delete.cshtml
@model StomatoloskaOrdinacija.Domain.DTOs.ZahvatDTO

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ZahvatDTO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Sifra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sifra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cijena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cijena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trajanje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trajanje)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StomatoloskaOrdinacija/Views/Zahvati/Details.cshtml
@model StomatoloskaOrdinacija.Domain.DTOs.ZahvatDTO

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ZahvatDTO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Sifra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sifra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cijena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cijena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trajanje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trajanje)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

StomatoloskaOrdinacija/Views/Zahvati/Detalji.cshtml
@model StomatoloskaOrdinacija.Domain.DTOs.ZahvatDTO

@{
    ViewBag.Title = "Detalji";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>Zahvat</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Sifra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sifra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cijena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cijena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trajanje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trajanje)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Uredi", "Uredi", new { id = Model.ID }, new { @class = "btn btn-default"}) |
    @Html.ActionLink("Povratak na popis", "Popis", null, new { @class = "btn btn-default" })
</p>

StomatoloskaOrdinacija/Views/Zahvati/Edit.cshtml
@model StomatoloskaOrdinacija.Domain.DTOs.ZahvatDTO

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ZahvatDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Sifra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sifra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sifra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cijena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CijenaID, Model.CijenaListDTO, "- Odaberite cijenu -", new { @class = "btn btn-default" })
                @Html.ValidationMessageFor(model => model.CijenaID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Trajanje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TrajanjeID, Model.TrajanjeListDTO, "- Odaberite trajanje -", new { @class = "btn btn-default" })
                @Html.ValidationMessageFor(model => model.TrajanjeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StomatoloskaOrdinacija/Views/Zahvati/Index.cshtml
@model IEnumerable<StomatoloskaOrdinacija.Domain.DTOs.ZahvatDTO>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Sifra)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cijena)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Trajanje)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Sifra)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Naziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cijena)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Trajanje)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

StomatoloskaOrdinacija/Views/Zahvati/Izbrisi.cshtml
@model StomatoloskaOrdinacija.Domain.DTOs.ZahvatDTO

@{
    ViewBag.Title = "Izbriši zahvat";
}

<h2>@ViewBag.Title</h2>

<h3>Jeste li sigurni da želite obrisati ovu stavku?</h3>
<div>
    <h4>Zahvat</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Sifra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sifra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cijena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cijena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trajanje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trajanje)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Izbriši" class="btn btn-danger" /> |
            @Html.ActionLink("Povratak na popis", "Popis", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

StomatoloskaOrdinacija/Views/Zahvati/Izradi.cshtml
@model StomatoloskaOrdinacija.Domain.DTOs.ZahvatDTO

@{
    ViewBag.Title = "Novi zahvat";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Sifra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sifra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sifra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cijena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CijenaID, Model.CijenaListDTO, "- Odaberite cijenu -", new { @class = "btn btn-default" }) 
                @Html.ActionLink("Dodaj cijenu zahvata", "Izradi", "CijenaZahvata", null, new { @class = "btn btn-default" })
                @Html.ValidationMessageFor(model => model.CijenaID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Trajanje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TrajanjeID, Model.TrajanjeListDTO, "- Odaberite trajanje -", new { @class = "btn btn-default" })
                @Html.ActionLink("Dodaj trajanje zahvata", "Izradi", "TrajanjeZahvata", null, new { @class = "btn btn-default" })
                @Html.ValidationMessageFor(model => model.TrajanjeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Izradi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Povratak na popis", "Popis", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StomatoloskaOrdinacija/Views/Zahvati/Popis.cshtml
@model IEnumerable<StomatoloskaOrdinacija.Domain.DTOs.ZahvatDTO>

@{
    ViewBag.Title = "Popis zahvata";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Novi zahvat", "Izradi", null, new { @class = "btn btn-default" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Sifra)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cijena)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Trajanje)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Sifra)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Naziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cijena)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Trajanje)
        </td>
        <td>
            @Html.ActionLink("Uredi", "Uredi", new { id=item.ID }, new { @class = "btn btn-default" }) |
            @Html.ActionLink("Detalji", "Detalji", new { id=item.ID }, new { @class = "btn btn-default" }) |
            @Html.ActionLink("Izbriši", "Izbrisi", new { id=item.ID }, new { @class = "btn btn-default" })
        </td>
    </tr>
}

</table>