StomatoloskaOrdinacija/Controllers/NaslovnicaController.cs
using StomatoloskaOrdinacija.Domain.DTOs;
using StomatoloskaOrdinacija.Domain.Services;
using StomatoloskaOrdinacija.Domain.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StomatoloskaOrdinacija.Controllers
{
    [Authorize]
    public class NaslovnicaController : Controller
    {
        RadnoVrijemeService radnoVrijemeService = new RadnoVrijemeService();
        NarudzbeService narudzbaService = new NarudzbeService();

        // GET: Naslovnica
        public ActionResult Kalendar()
        {
            NarudzbaRadnoVrijemeVM viewModel = new NarudzbaRadnoVrijemeVM();
            viewModel.NarudzbaDTOList = GetNarudzbaList();
            viewModel.RadnoVrijemeDTO = GetRadnoVrijeme();

            return View(viewModel);
        }

        public List<NarudzbaDTO> GetNarudzbaList()
        {
            List<NarudzbaDTO> narudzbaDTO = narudzbaService.GetPopisNarudzba();

            return narudzbaDTO;
        }

        public RadnoVrijemeDTO GetRadnoVrijeme()
        {
            var id = radnoVrijemeService.GetRadnoVrijemeId();
            RadnoVrijemeDTO radnoVrijemeDTO = radnoVrijemeService.GetRadnoVrijemeById(id);

            return radnoVrijemeDTO;
        }
    }
}

StomatoloskaOrdinacija/Controllers/RadnoVrijemeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StomatoloskaOrdinacija.DAL;
using StomatoloskaOrdinacija.Domain.DTOs;
using StomatoloskaOrdinacija.Domain.Services;

namespace StomatoloskaOrdinacija.Controllers
{
    public class RadnoVrijemeController : Controller
    {
        private OrdinacijaDb db = new OrdinacijaDb();
        RadnoVrijemeService service = new RadnoVrijemeService();

        // GET: RadnoVrijeme/Edit/5
        public ActionResult Uredi(/*int id*/)
        {
            var id = service.GetRadnoVrijemeId();
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RadnoVrijemeDTO radnoVrijemeDTO = service.GetRadnoVrijemeById(id);
            if (radnoVrijemeDTO == null)
            {
                return HttpNotFound();
            }
            return View(radnoVrijemeDTO);
        }

        // POST: RadnoVrijeme/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Uredi([Bind(Include = "ID,VrijemeOd,VrijemeDo")] RadnoVrijemeDTO radnoVrijemeDTO)
        {
            if (ModelState.IsValid)
            {
                service.EditRadnoVrijeme(radnoVrijemeDTO);

                return RedirectToAction("Kalendar", "Naslovnica");
            }
            return View(radnoVrijemeDTO);
        }

        //// GET: RadnoVrijeme/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    RadnoVrijemeDTO radnoVrijemeDTO = db.RadnoVrijemeDTOes.Find(id);
        //    if (radnoVrijemeDTO == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(radnoVrijemeDTO);
        //}

        //// POST: RadnoVrijeme/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    RadnoVrijemeDTO radnoVrijemeDTO = db.RadnoVrijemeDTOes.Find(id);
        //    db.RadnoVrijemeDTOes.Remove(radnoVrijemeDTO);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StomatoloskaOrdinacija/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Stomatološka ordinacija</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/ej/web/flat-lime/ej.web.all.min.css")
    @Styles.Render("~/Content/ej/web/responsive-css/ejgrid.responsive.css")
    @Scripts.Render("~/Scripts/jquery-3.3.1.min.js")
    @Scripts.Render("~/Scripts/jsrender.min.js")
    @Scripts.Render("~/bundles/ej")


</head>
<body>
    @if (User.Identity.IsAuthenticated)
    {
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Stomatološka ordinacija", "Kalendar", "Naslovnica", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Pacijenti", "Popis", "Pacijenti")</li>
                        <li>@Html.ActionLink("Zahvati", "Popis", "Zahvati")</li>
                        <li>@Html.ActionLink("Radno vrijeme", "Uredi", "RadnoVrijeme")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    }
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Stomatološka ordinacija</p>
            </footer>
        </div>
        @Html.EJ().ScriptManager()
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/Scripts/ej/i18n/ej.culture.hr-HR.min.js")
        @Scripts.Render("~/Scripts/ej/l10n/ej.localetexts.hr-HR.js")

        @RenderSection("scripts", required: false)
    </body>
</html>